### ISSUE TITLE
Preso Repo?

### ISSUE THREAD

**Issue by fawcett** [maptimemsp/presentations#2]
I don't really know how we want to handle presentations, but I think that it is nice to have a place for people like Kat to post their slides when they don't have their own blog/repo/website/platform, etc.

If people want to push their presentations up to the Maptime HQ site, we can do that too, but I am sure that sometimes, they just want to keep it local...

Thoughts?

**Comment by lpuhl** [comment]
There is a section for files on the Meetup site—I think we should put the presentation files there, too, so people don't have to deal with an unfamiliar interface to download them. (I think even the word "Github" can sound intimidating to the newbie, i.e. me.)

And, like you suggested, we can also give people the option of making their presentation available to Maptime worldwide.

**Comment by geospatialem** [comment]
I know other Maptime Chapter's use their own GitHub repo as opposed to the main Maptime one. I agree, in that we should show off the awesomeness that we're doing in Minnesota!

The only thing that's kind of a drag is its hard to share these things on GitHub if they aren't in PDF, or a similar format. But, for the most part we should be able to convert most presentations to PDF. I'll add in my presentations from February, and September, too (this weekend).

If we do keep the current organization with GitHub, should we try and organize by date, or leave as-is for now?

P.S. @lpuhl - This is an awesome first step in testing out GitHub. @fawcett and I can help you learn as we go! :smile_cat:

**Comment by fawcett** [comment]
I think that we can close this one.
