### ISSUE TITLE
February presentations

### ISSUE THREAD

**Issue by fawcett** [maptimemsp/presentations#8]
I am creating this as a reminder, not a shaming agent  ;  /  

If we can get the presentations from Nat and David, it would be great to get them into the repo.

**Comment by geospatialem** [comment]
HAHA. Yes, I'm on this, hopefully before next week's meeting. :wink:

**Comment by geospatialem** [comment]
Added Nat's presentation with commits 746b5d8551c950f3d0b51697c8865d2de2672c45 and 029551f1a0fa052bb5017c12d7578248ff113de6. 

David M. used notes, and demos throughout his presentation, if he sends over anything I'll add it in. Otherwise this closes this should close the issue.
